# models/knowledge_point.py
from pydantic import BaseModel
from datetime import datetime
from typing import Optional, List

class KnowledgePoint(BaseModel):
    id: Optional[str] = None  # Auto-generated by database (e.g., MongoDB ObjectId)
    name: str  # e.g., "Quadratic Equations"
    parent_id: Optional[str] = None  # For hierarchical structure (e.g., "Algebra" as parent)
    description: Optional[str] = None
    created_at: datetime = datetime.utcnow()
    tags: List[str] = []  # e.g., ["algebra", "equations"]